In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [8]:
price = {
    "sqft" : [500,700,900,1100,1300],
    "price" : [100000,150000,180000,220000,260000]
}

In [9]:
df = pd.DataFrame(price)

In [10]:
df

   sqft   price
0   500  100000
1   700  150000
2   900  180000
3  1100  220000
4  1300  260000

In [11]:
df.head

<bound method NDFrame.head of    sqft   price
0   500  100000
1   700  150000
2   900  180000
3  1100  220000
4  1300  260000>

In [13]:
df.tail

<bound method NDFrame.tail of    sqft   price
0   500  100000
1   700  150000
2   900  180000
3  1100  220000
4  1300  260000>

In [15]:
X= df[["sqft"]]
y = df["price"]

In [16]:
X

   sqft
0   500
1   700
2   900
3  1100
4  1300

In [17]:
y

0    100000
1    150000
2    180000
3    220000
4    260000
Name: price, dtype: int64

In [20]:
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state= 42)

In [21]:
X_train

   sqft
4  1300
2   900
0   500
3  1100

In [22]:
X_test

   sqft
1   700

In [24]:
model = LinearRegression()

In [25]:
model.fit(X_train,y_train)

LinearRegression()

In [29]:
y_pred=model.predict(X_test)

In [30]:
newpredict = model.predict([[1000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [31]:
newpredict

array([200000.])

In [33]:
sush = model.coef_

In [34]:
sush

array([200.])

In [37]:
nish = model.intercept_

In [38]:
nish

np.float64(0.0)

In [39]:
print("the regression Equation is: ","Y",model.coef_,"* X + ",model.intercept_)

the regression Equation is:  Y [200.] * X +  0.0